### ISSUE TITLE
Potentially update the way we handle uncertainties that impact the selection

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#123]
As discussed in PR #121, it would be good to think about the way we handle the systematics that affect the selection (e.g. the jet energy scale and jet energy resolution). These uncertainties are a bit more complicated than the others, since the effects have to be propagated throughout the processor. 

As explained by @GonzalezFJR, there are at least three ways this could be handled:
> So one option is re-running the full analysis changing the pT of the muons , as in Andrea's version (there are other analysis with coffea that do this). The other option would be adding tags for the muon pT to basically everything in the analysis (categories, number of jets, HT...) and fill the nominal/up/down axis depending on the chosen muon pT. A third option would be implementing a 'for' loop at the beginning of the analysis, before the muon selection, and remove from the loop those elements that are not affected by muon pT (for example, the electron selection).

The current method (implemented by @andrea21z in PR #121) is option 1. However, it seems option 3 might be the most optimal, since we could run everything all together in one run of the processor, instead of having to run separately for some of the systematics. We could then handle the other similar systematics as part of the same loop. So, this is something we might want to move to in the future.

**Comment by bryates** [comment]
In general, option 3 might be the way to go. I'm always weary with loops in python as a potential speed bottleneck. We can investigate it when we get to that point. List/dictionary comprehensions are always a good option, since they execute in the underlying C code.

**Comment by bryates** [comment]
> In general, option 3 might be the way to go. I'm always weary with loops in python as a potential speed bottleneck. We can investigate it when we get to that point. List/dictionary comprehensions are always a good option, since they execute in the underlying C code.

Plus, these loops usually wind up only taking milliseconds, so probably not a big deal.

**Comment by andrea21z** [comment]
> > In general, option 3 might be the way to go. I'm always weary with loops in python as a potential speed bottleneck. We can investigate it when we get to that point. List/dictionary comprehensions are always a good option, since they execute in the underlying C code.
> 
> Plus, these loops usually wind up only taking milliseconds, so probably not a big deal.

Ok, so I will start to work on the implementation of the loop.

**Comment by kmohrman** [comment]
Linking this issue to PR #134 for reference.
