### ISSUE TITLE
Final output histogram takes too long to write to disk

### ISSUE THREAD

**Issue by btovar** [TopEFT/topcoffea#14]
(In commit 74e5985cb4be619314b13c3f1bd7730a12cd77f7, work-queue-ak1 branch.)

The final histogram file currently generated by `run.py` and `work_queue_run.py` takes too long to write to disk. In test runs for less than five input files, writing to the output file does not finish in less than 30min. In such cases, memory consumption was above 100G, and manually terminated.

This is likely a symptom of some other issue related to how the histograms are generated.

**Comment by kmohrman** [comment]
Hi @btovar, I've been going through the old issues in this repository, and am wondering if we can close this one? Based on Issue #15 it looks like it might have been addressed by @klannon's PR #18 back in April.
