### ISSUE TITLE
Check baseline njets fits after fixing overflow bug

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#147]
As described in PR #145, the njets histograms that the datacard maker produced had the last njets bin as the overflow bin. Since combine does not fit the overflow bins, it was missing the last bin in each of our lepton categories. This issue is fixed in PR #145, but it would be good to have a comparison of the baseline njets fits from before and after the bug fix for reference, so that we know the size of the effect.

**Comment by bryates** [comment]
Here's the comparison
http://www.crc.nd.edu/~byates2/coffea/master/1D/njet.runII.overflow/BestScanPlot.pdf
and the breakdown
```
FoM (<1 is better)
WC CI_low CI_high
cQq13 1.022
cQq83 1.023
cQq11 1.021
ctq1 1.012
cQq81 1.047
ctq8 1.023
ctt1 1.21
cQQ1 1.225
cQt8 1.213
cQt1 1.211
ctW 1.001
ctZ 1.01
ctp 1.022
cpQM 1.007
ctG 1.046
cbW 1.025
cpQ3 1.04
cptb 1.029
cQl3i 1.006
cQlMi 1.034
cQei 1.036
ctli 1.037
ctei 1.036
ctlSi 1.038
ctlTi 1.036
```
So we seem to get about 2-4% worse.

**Comment by kmohrman** [comment]
Just to make sure I'm following, when you say we get worse, you mean _with_ the bug it's worse, right? So after fixing the bug we get a few percent (up to 20%) better?

**Comment by bryates** [comment]
> Just to make sure I'm following, when you say we get worse, you mean _with_ the bug it's worse, right? So after fixing the bug we get a few percent (up to 20%) better?

No, this is _after_ the fix. The FoM is `(CI_(new high) - CI_(new low)) / (CI_(old high) - CI_(old low))`

**Comment by kmohrman** [comment]
So, you are saying the fix makes limits get worse? That is a bit confusing to me, as the bug meant we were dropping bins, so I would have thought that after the fix the limits would have to get better.

**Comment by kmohrman** [comment]
Especially since the WCs with large changes are the ones from the four-heavy category (i.e. the ones that affect tttt). It would make a lot of sense that they get better when we include the high jet multiplicity bins that we were missing before. But I am really confused about why they would get worse when including higher jet multiplicity bins...

**Comment by kmohrman** [comment]
In your plot it also looks like the ranges labeled "master" are wider than the ones labeled "overflow", so that seems consistent with what I'd expect. Maybe I'm just misinterpreting what you meant by which ones were before and which ones were after.

So, probably I'm just mixed up on my end, sorry. Just to make sure things are clear, I'm wondering if you could confirm whether the limits get better, or whether the limits get worse (_after_ fixing the bug)?

**Comment by bryates** [comment]
Ah, I got the FoM backwards! It's showing `(CI_(old high) - CI_(old low)) / (CI_(new high) - CI_(new low))` meaning `>1` is better.

**Comment by kmohrman** [comment]
Ah, ok! So the limits get better after the fix, by a few percent for most WCs, and up to about 20% for some of the four-heavy WCs. Okay, that's really good to know, and I think consistent with what we'd expect.

**Comment by bryates** [comment]
I'll post this again for completeness.
Here's the comparison
http://www.crc.nd.edu/~byates2/coffea/master/1D/njet.runII.overflow/BestScanPlot.pdf
and the breakdown
```
FoM (>1 is better)
WC FoM
cQq13 1.022
cQq83 1.023
cQq11 1.021
ctq1 1.012
cQq81 1.047
ctq8 1.023
ctt1 1.21
cQQ1 1.225
cQt8 1.213
cQt1 1.211
ctW 1.001
ctZ 1.01
ctp 1.022
cpQM 1.007
ctG 1.046
cbW 1.025
cpQ3 1.04
cptb 1.029
cQl3i 1.006
cQlMi 1.034
cQei 1.036
ctli 1.037
ctei 1.036
ctlSi 1.038
ctlTi 1.036
```
