### ISSUE TITLE
Random changes in bin contents

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#168]
We've been noticing random differences in the `pkl` files after successive runs. Most are small, which can probably be attributed to the Rochester corrections applying smearing with `np.random.rand()`. However, sometimes the differences can be `O(0.1%)`. It's possible these runs were just unlucky, and picked large random numbers. As a test, I fixed the random seed to 0, but this is not a long term solution.

We need a better way to determine the random seed, or a method without numbers (if possible).

**Comment by andrea21z** [comment]
That's a good point. I implemented the rochester corrections using the recommended method: https://gitlab.cern.ch/akhukhun/roccor.
I'm not sure if a change of ~0.1% is expected, but fixing the seed may not be such a bad solution.

**Comment by kmohrman** [comment]
As discussed at the April 8, 2022 group EFT meeting, we do not feel it is necessary to address this issue at this time. The main concern was that the random changes would make things difficult to track while doing validation. However, as we seem to have managed with this so far, we do not think it is probably necessary to address the issue at this point.
