### ISSUE TITLE
Missing NAODv9 Skims

### ISSUE THREAD

**Issue by Andrew42** [TopEFT/topcoffea#212]
This issue is in relation to PR #211, which introduced the skimmed MC background samples. There were two datasets that were skipped when producing the skims:
```
/ZZTo4L_13TeV_powheg_pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM
/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18NanoAODv2-106X_upgrade2018_realistic_v15_L1v1-v1/NANOAODSIM
```
They were skipped because NAODv9 versions are still not yet available. Once they become available we will want to update our json files and produce skims for them.

**Comment by kmohrman** [comment]
Closed by PR #218.
