### ISSUE TITLE
Determine if we need the up/down variations for the Rochester corrections

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#233]
At the Friday April 15 weekly group meeting, @rgoldouz mentioned that it is possible that it may not be recommended to include the up/down variations for the Rochester corrections. It would be good if someone could check into this. @andrea21z, is this something you'd be able to do?

**Comment by Andrew42** [comment]
So I was messing around with (crudely) benchmarking the `topeft` processor and found some interesting results relating to the Rochester corrections. It appears as though a large fraction of the _entire_ processing time is concentrated in just two lines of code that are a part of the Rochester correction computation.

Some notes and caveats to keep in mind regarding these timings:

- Dataset: ttllJet (skimmed)
- Num. Files: 8
- Num. Chunks: 8
- Num. Workers: 8

Timings computed inside the processor were summed up and divided by the number of chunks. The time intervals were determined using `time.time()`. Rows marked with an asterisk (`*`) denote timings the span multiple lines of code and can be a superset of some of the other rows in the table. The percentages given next to each timing is the fraction of the "Total" row. All tests were done using the `futures` executor and ran from `earth`.

| Chunksize | 500 | 5k  | 50k | 100k |
| --- | --: | --: | --: | --: |
| [roch_calcs_init*](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/modules/corrections.py#L477-L481) |  0.04 s   (0%) |  0.12 s   (0%) |   0.76 s  (<1%) |   1.64 s   (1%) |
| [mc_kspread](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/modules/corrections.py#L483)            |  0.11 s   (0%) |  0.13 s   (0%) |   0.32 s   (0%) |   0.56 s   (0%) |
| [mc_ksmear](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/modules/corrections.py#L484)             |  0.18 s   (0%) |  0.19 s   (0%) |   0.28 s   (0%) |   0.43 s   (0%) |
| [errspread](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/modules/corrections.py#L485)             |  9.19 s  (15%) |  9.67 s  (14%) |  14.21 s  (13%) |  19.08 s  (13%) |
| [errsmear](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/modules/corrections.py#L486)              | 15.25 s  (24%) | 15.66 s  (23%) |  20.96 s  (20%) |  26.19 s  (18%) |
| [roch_total*](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeft.py#L258-L260)             | 25.15 s  (40%) | 26.16 s  (39%) |  36.93 s  (35%) |  48.28 s  (34%) |
| [fill_call](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeft.py#L836)                    |  1.44 s   (2%) |  1.64 s   (2%) |   3.16 s   (3%) |   4.92 s   (3%) |
| [process_total*](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeft.py#L114)               | 47.33 s  (76%) | 50.87 s  (76%) |  86.65 s  (82%) | 122.73 s  (86%) |
| [Total](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/run.py#L206-L208)                      | 62.30 s (100%) | 67.36 s (100%) | 105.73 s (100%) | 142.35 s (100%) |

As we can see, it appears as though the `errspread` and `errsmear` calculations alone account for 35-40% of the total processing time. What's more, these computations are only needed if we want to include the UP/DOWN uncertainties on the Rochester corrections (the topic of this very issue!). The code implemented as is, needlessly calculates the `errspread` and `errsmear` even when you don't want to include/compute any systematic variations, but if we decide to drop this systematic then we wouldn't even need to insert any extra `if` statements and could instead just remove the lines altogether.

After talking with @kmohrman, she said that we typically run with a chunksize of 50k, so we might expect to gain a speedup of around 30%, which would be useful for turnaround times on producing the histograms. It would also have an even bigger effect for any cases where someone is doing short development tests (e.g. using the `futures` executor). Just some extra considerations for deciding whether we want to drop this systematic or not.

**Comment by andrea21z** [comment]
I have been reading the [recommendations](https://gitlab.cern.ch/akhukhun/roccor/-/blob/master/README) and, if I understand correctly, if the effect of the uncertainties is negligible they can probably be neglected. 
@kmohrman, is this the case of our analysis?

**Comment by kmohrman** [comment]
Thanks for checking on this @andrea21z. I'm not sure if the effect is completely negligible, but I think that's something we'll probably want to evaluate (especially given @Andrew42's study above).

I guess one way to check would be to run the fit with and without the systematics included. If there is no difference in the limits, I guess that means the effect is probably negligible. However, we should probably wait to do this check until the rest of the uncertainties have stabilized a bit. 

But if we are going to consider dropping the up/down variations for this systematic, I think another thing we might want to know (just for references) is the size of the up/down variations. @andrea21z, do you happen to know the numbers for this?

**Comment by andrea21z** [comment]
> Thanks for checking on this @andrea21z. I'm not sure if the effect is completely negligible, but I think that's something we'll probably want to evaluate (especially given @Andrew42's study above).
> 
> I guess one way to check would be to run the fit with and without the systematics included. If there is no difference in the limits, I guess that means the effect is probably negligible. However, we should probably wait to do this check until the rest of the uncertainties have stabilized a bit.
> 
> But if we are going to consider dropping the up/down variations for this systematic, I think another thing we might want to know (just for references) is the size of the up/down variations. @andrea21z, do you happen to know the numbers for this?

I guess it deppends on the sample/year/channel you look... I thought you had checked some plots with all the up/down variations and the MuonES unc. were small. When I implemented the corrections I checked it in Drell Yan and data 2018 and the effect of the unc. were small.

![image](https://user-images.githubusercontent.com/43755790/164240276-e3e2485f-6f71-4f44-a071-bbdf34d8be07.png)

**Comment by kmohrman** [comment]
Thanks @andrea21z! I agree that looks pretty small. I'm wondering if you could quantify that (i.e. get the percent change for the up/down Rochester corrections compared to the nominal Rochester) for this example (or any other example you happen to have on hand), if it's not too much work?

**Comment by andrea21z** [comment]
> Thanks @andrea21z! I agree that looks pretty small. I'm wondering if you could quantify that (i.e. get the percent change for the up/down Rochester corrections compared to the nominal Rochester) for this example (or any other example you happen to have on hand), if it's not too much work?

I have done some checks and the variations are less than 0.05%

**Comment by kmohrman** [comment]
As discussed at the group meeting Friday April 22nd, the impact of these uncertainties on the fit seems to be negligible (see [these slides](https://indico.cern.ch/event/1123572/contributions/4843662/attachments/2430140/4161039/some_updates_apr_22_2022.pdf) for details). This combined with @andrea21z's studies above led us to the decision that we should drop the Rochester uncertainties. 

@andrea21z or @Andrew42, would one of you be able to make a PR to remove these uncertainties?

**Comment by Andrew42** [comment]
Sounds good, I'll create the branch and make the PR. It should be pretty quick, but will certainly want someone familiar with the systematics to look it over and make sure I don't miss something obvious.

**Comment by kmohrman** [comment]
Closed by PR #241.
