### ISSUE TITLE
Check xsec numbers for ttbar samples

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#254]
We should track down the right cross sections for the `TTTo2L2Nu` and `TTToSemiLeptonic` samples. In our [xsec.cfg](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/cfg/xsec.cfg#L19-L21) they are listed as 88.28769753 and 365.3994209, but it is not clear where these numbers come from. Looking through AN 19-127 (the AN we based our charge flip measurement method on), and they list the cross sections for these processes as 88.3419 and 365.4574, and they cite [this twiki](https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO). However, that twiki says in red capital letters at the top "OUTDATED RECOMMENDATIONS, PAGE UNDER CONSTRUCTION", so it's not clear if we should be using numbers from it.

**Comment by Andrew42** [comment]
See PR #255
