### ISSUE TITLE
Sum of weights for non-EFT process

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#27]
Forcing the storage type to `Double`
https://github.com/TopEFT/topcoffea/blob/4c53b0be876bd3afab1a9e274e12b87b2650aa66/topcoffea/modules/histEFT.py#L101
means we lose the sum of weights, even in the non-EFT samples. The data is simply `sqrt(N)`, but the nonprompt leptons have an MC component subtracted off
https://github.com/TopEFT/topeft/blob/3ae0f05890a129aaa226efeaec949d13e1778468/topeft/modules/dataDrivenEstimation.py#L115-L129.
This means the nonprompt templates **have no uncertainties**, but we still ask combine to compute the MC stat errors. This is likely causing the remaining discrepancy in the limits when compared to the master branch on the TopEFT repo.

**Comment by bryates** [comment]
@btovar do you have any thoughts on this? Just changing the default type to `Weight` (and disabling the `Double` [check](https://github.com/TopEFT/topcoffea/blob/4c53b0be876bd3afab1a9e274e12b87b2650aa66/topcoffea/modules/histEFT.py#L102-L103)) isn't enough. I think the way [`_ak_rec_op`](https://github.com/TopEFT/topcoffea/blob/4c53b0be876bd3afab1a9e274e12b87b2650aa66/topcoffea/modules/sparseHist.py#L327-L347) builds things is incompatible with `Weight`. As an alternatives, we could just store the sum of square of weights (at the SM) in a dict or another dense axis.

**Comment by btovar** [comment]
@bryates I think that was the idea, to record it separately from that double axis. As I understood it, `Weight` is going to do the wrong thing for the EFT hists.

**Comment by bryates** [comment]
> @bryates I think that was the idea, to record it separately from that double axis. As I understood it, `Weight` is going to do the wrong thing for the EFT hists.

Right, we don't really need it for the actual EFT histograms (sine it would be a quartic function), but we'll need it for the SM terms that are subtracted off later one. Do you know of a coinvent way to add another axis, or would it be easier (but maybe less efficient) to just save another histogram with the weights^2?

**Comment by btovar** [comment]
I think it would be much easier to have another histogram with the weights. The way the new histograms work make it hard to have special treatment of some axis.

**Comment by bryates** [comment]
> I think it would be much easier to have another histogram with the weights. The way the new histograms work make it hard to have special treatment of some axis.

Ok thanks. I was starting to suspect that after trying to hack something in.
