### ISSUE TITLE
Combine run.py and work_queue_run.py

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#288]
Not a high priority item, but It might be good to combine run.py and work_queue_run.py into a single run script. We could switch between executors using a flag, as we have implemented for the run scripts for all of our newer processors (see e.g. `run_sow.py` and `run_flip.py`). This makes things much easier to maintain, since edits to options and updates only have to be made in one place. (While we're at it, might as well  also make the new combined run script have consistent 4 space indentation.)

**Comment by ywan2** [comment]
Updated version of `run_executor.py` is created on another branch `combine-executors`, which is based of branch `technical_improvements`. (The the above comment has old `combine-runscript` based off `master` branch which is not what we wanted).

See branch comparison between `combine-executors` and `technical_improvements` [here](https://github.com/TopEFT/topcoffea/compare/technical_improvements...combine-executors).

The instruction to run it ia the same as the above comment.

**Comment by kmohrman** [comment]
Closed by PR #354
