### ISSUE TITLE
Number of cores in work-queue

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#37]
We currently request 2 cores in work-queue
https://github.com/TopEFT/topcoffea/blob/2df1290ca69d242255e05ab9dfe4a696f31754a1/analysis/topEFT/work_queue_run.py#L142
but do we actually use 2?

**Comment by kmohrman** [comment]
We only need 1 core for each task (as verified by running the code with the `cores` set to 1 and making sure it does not crash), so I've modified this in the wq run script [here](https://github.com/TopEFT/topcoffea/commit/735c211203ce90c7bc21b5b54af1387bb9dfbeca).
