### ISSUE TITLE
Stop Pinning Python Version?

### ISSUE THREAD

**Issue by klannon** [TopEFT/topcoffea#60]
I don't think we need to pin our Python version anymore.  I just tried the conda recipe without `python=3.8.3` and it worked just fine (at least in my quick test) with my enviroment getting Python 3.9.6.  As far as I can tell, neither `Coffea` or `ndcctools` requires an old version of Python.  Many months ago we needed to pin the Python version to prevent a crash, but as far as I can tell, that issue has been resolved so it's no longer needed.  If there's agreement, then this issue can be closed by committing a change to the README to remove `python=3.8.3` from the recipe.

**Comment by kmohrman** [comment]
The specification of version 3.8.3 has been removed in [this commit](https://github.com/TopEFT/topcoffea/commit/31252f571955f115e63c9b899eceeabc05106186).
