### ISSUE TITLE
Possible Bug in BTagging Working Point?

### ISSUE THREAD

**Issue by klannon** [TopEFT/topcoffea#68]
It seems like [this](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeft.py#L169-L179) code has a bug in it because 2016 and 2018 would use the same working points.  @rgoldouz was going to check the appropriate Twikis and might post more information here.

**Comment by kmohrman** [comment]
Twiki from Reza: https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation106XUL18

**Comment by klannon** [comment]
One additional thought: we should probably avoid cases in which "else" corresponds to a specific year.  In other words avoid the following:
```py
if year == "2016":
  do.something_for_2016()
else:
  # This is for 2017
  do.something_for_2017()
```
Instead, it should look like this:
```py
if year == "2016":
  do.something_for_2016()
elif year == "2017":
  do.something_for_2017()
else:
  raise ValueError("Don't know how to handle year = {}".format(year))
```

This will avoid silent bugs, like it someone accidentally sets `year = 2106`.  If the first version of the code, which is like what we have now, `year=2106` would cause the 2017 action to happen, while in the second version, it would produce an error.

**Comment by klannon** [comment]
Here is the Twiki with all the years in it: https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation

Except here *all* is all except 2016.  It seems like those numbers haven't been put in the Twiki yet?  🤨

**Comment by kmohrman** [comment]
This issue has been partially addressed in [this commit](https://github.com/TopEFT/topcoffea/commit/5aceaddf2dbc61acc37f3acbe8401e430fabef0e#diff-c72c207af2deec6e89e9ae850c8b24f4decb3fe908c6cbb338e6d48dc12968d2) on the `consolidate-parameters` branch ([PR](https://github.com/TopEFT/topcoffea/pull/67) here). While the UL16 numbers do not seem to exist yet, we are using the 2016 legacy numbers linked from the twiki @klannon pointed to above (now documented in a README in the `topcoffea/json` directory). 

We should probably leave the issue open until the UL16 (and UL16APV?) are available.

**Comment by kmohrman** [comment]
I'm wondering if we can close this issue. @andrea21z, could you confirm that we are using the most up to date btag WPs at this point? If so, we can probably go ahead and close this.

**Comment by andrea21z** [comment]
> I'm wondering if we can close this issue. @andrea21z, could you confirm that we are using the most up to date btag WPs at this point? If so, we can probably go ahead and close this.

yes, we can close this issue
