### ISSUE TITLE
Pinned Python in topeftenv.py

### ISSUE THREAD

**Issue by klannon** [TopEFT/topcoffea#69]
Now that we've unpinned `python` in our recipe, I was surprised to see it still being pinned in my WQ environment.  I tracked it down to [this line](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeftenv.py#L25).  Trying to understand how this code actually worked raised some questions in my mind:
1. It looks like the worker environment is being built from "scratch" with [`conda install`](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeftenv.py#L53) based on the contents of [this json](https://github.com/TopEFT/topcoffea/blob/master/analysis/topEFT/topeftenv.py#L21-L35).  Is that right?
2. Assuming the answer to (1) is yes, then it means that this json needs to be updated anytime we change a dependency for the worker.  In other words, if we added a new python import in the `topcoffea` library or `topeft.py` processor, we would need to add it here or it would be missing.  Right?
3. Because `conda install` is being used, the version of what gets installed would not necessarily have to match what's in your current conda environment.  E.g. if you had a conda environment based on `coffea 0.7.3`, and you ran the code in `topeftenv.py` today, on your worker, you'd have `coffea 0.7.5`, right?
4. Is the reason we need the json specifying the base environment because you don't want to package up every last piece of the users active conda environment because (for example) the worker node doesn't need `juptyerlab`, etc.?

At a minimum, it seems like we need to modify the json to unpin Python, like we did in the main recipe.  However, if the answer to some or all of the "right?" questions above is "yes," then I wonder if we can't do better.  At a minimum, it seems like `topeftenv.py` should enforce packaging the same version of each package as what's stored in the users own conda environment.  This would remove the need to hardcode a pinned version in the json and would make sure the worker doesn't accidentally end up with a different version of a package than what the user has locally.

@btovar, what do you think?

**Comment by btovar** [comment]
+1 on topeftenv checking for the current version of python.

In fact this is how we do it when constructing the environment for the wq coffea CI test, so I just need to adapt that code to topeftenv.

**Comment by kmohrman** [comment]
Closed by PR #70.
