### ISSUE TITLE
Move to NAOD v9

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#87]
Our privately produced NAOD currently corresponds to v8 (as we produced it with `CMSSW_10_6_19_patch2 `, using the NAOD configs generated with the `NanoAODv2` versions of the `cmsDriver` commands listed on [this twiki](https://twiki.cern.ch/twiki/bin/view/CMS/PdmVMcCampaigns)). Once the appropriate `cmsDriver` commands for v9 are included on that twiki, we should remake the NAOD.

**Comment by rgoldouz** [comment]
Hi @kmohrman , It is not needed to wait for the twiki to be updated. You can easily find the commands for generating nanoAOD config files from mcm.
Just choose one of the simulate samples and find the submitted PrepID in MCM, for example
https://cms-pdmv.cern.ch/mcm/requests?prepid=TOP-RunIISummer20UL17NanoAODv9-00001&shown=6442455051

in Action column you will find the setup command,
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/TOP-RunIISummer20UL17NanoAODv9-00001

So you have the cmsDriver command.

Please let me know if you have any question.

Thanks,
Reza

**Comment by kmohrman** [comment]
Thanks @rgoldouz. That's a good point, and it is something that's been on my to-do list for quite some time (but I have not gotten to it yet). I will definitely let you know of any questions once I attempt to produce the new configs, thanks!

**Comment by kmohrman** [comment]
Closed with PR #148.
